megaease/easeprobe

README.md, conf/conf.go, probe/base/base.go, probe/ssh/endpoint.go, probe/ssh/endpoint_test.go, probe/ssh/ssh.go
- Support the bastion/jumper server 
- SSH host support  `user@server:port` scheme
- recursively reflect the probe interface in config structure
- remove the "known_hosts".
- refine the probe log code - remove the duplication code
=> support the bastion/jumper server for SSH probe

README.md, conf/conf.go, notify/base/base.go, notify/slack/slack.go, probe/host/host.go, probe/ssh/endpoint.go, probe/ssh/endpoint_test.go, probe/ssh/ssh.go, report/sla.go
Support the host probe, the configuration example as below.
The feature probe the CPU, Memory, and Disk usage, if one of them exceeds the threshold, then mark the host as status down.
```yaml
host:
bastion: # bastion server configuration
aws:
host: ubuntu@example.com
key: /path/to/bastion.pem
servers:
- name : aws server
bastion: aws #  <-- bastion server id
host: ubuntu@172.20.2.202:22
key: /path/to/server.pem
threshold:
cpu: 0.80  # cpu usage  80%
mem: 0.70  # memory usage 70%
disk: 0.90  # disk usage 90%
- name : My VPS
host: user@example.com:22
key: /Users/user/.ssh/id_rsa
```
=> feat(probe): support host resource usage probe

README.md, probe/client/mysql/mysql.go, web/server.go
fix issue #56 
- fix the connection leak - run  `row.Close()` after the `sql.Query()` 
- fix the null pointer error if the `sql.Open()` return error
- typo fix and `go fmt`
=> bug-fixing: mysql client connection leaks

probe/host/host.go
Started reading the code to get a better understanding of the application and i noticed that the df command can be improved a bit.
this change makes df stop reporting errors for fuse filesystems such as `df: /run/user/1000/doc: Operation not permitted` and also limits the usage reported by df to only the root filesystem `df -h /`
=> Redirect `df` stderr to /dev/null and limit to rootfs `/`

README.md, conf/conf.go, daemon/daemon.go, global/easeprobe.go, global/global.go, notify/discord/discord.go, probe/client/mysql/mysql.go, probe/common.go, probe/http/http.go, report/common.go, report/result.go, report/sla.go
This PR address the issue  #76  
simply copy the same feature from `shell` and `ssh` probe.
=> Support to Check the HTTP Response Text

README.md, conf/conf.go, probe/data.go
Support to configure the max of SLA data file backups. default: 5
If set to a negative value, keep all backup files
```yaml
sla:
data: /tmp/data/data.yaml
backups: 20
```
keep addressing the issue  #69
=> Support max backups of SLA data files

cmd/easeprobe/main.go, conf/conf.go
If the configuration is:
```yaml
settings:
sla:
data: data.yaml
```
The EaseProbe would raise an error 
```
Failed to save the SLA data to file: mkdir : no such file or directory
```
Because the `dir` string we pass to `os.MkdirAll(dir, 0755)` is empty. 
this is a fix for this bug.
=> bug-fixing: mkdir error  when the SLA data file is not specified the path

cmd/easeprobe/main.go, go.mod, web/server.go
This PR addresses the issue #89 
1)  splite the `http.LisentAndServe()` to  `net.Lisen()` and `http.Serve()`
2) move the `web.Server()` before starting the probe and notifcation, so that easeprobe can be exited safely.
=> EaseProbe exits if the web server address already in use

cmd/easeprobe/main.go
This PR removes SIGINT from our handlers and brings back instant stop when CTRL+C is pressed
fixes #88
=> remove sigint from our main handlers

README.md, web/server.go
- remove the code that calculates the auto-refresh time from the probes.
- Add the refresh parameter in URL - `http://localhost:8181/?refersh=30s`
fix issue #93
=> Remove refresh time calculation from probe, and add the refresh parameter in URL

README.md, cmd/easeprobe/main.go, conf/conf.go, global/global.go, probe/data.go, probe/results_test.go
This PR does
Cases 
* Case One: No data file is configured, then we use the $CWD/data.yaml as the default.
* Case Two: data file name configured, but not configured the directory, such as: `data: mydatafile.yaml`, we use the `$CWD/mydatafile.yaml`
* Case Three: the full path has been configured. we just simply use the full path.
* Case Four: the disable flag configured `-` eg `data : -` , then we disable the data file.
=> Disable SLA persistence when conf.Settings.SLAReport.DataFile is "-"

conf/conf.go, conf/conf_test.go
This PR adds test cases for `conf/conf.go` and changes the detection method of isExternalUrl 
edit: _I changed the scope of the PR to only include 1 module at a time, so that fixes for the test cases can also be included as pair_
=> add two conf/conf.go test cases and update isExternalURL

probe/data.go
When the number of existing data files is less than the backup limit, `probe.CleanDataFile` does not need to perform any action. Currently, this condition is covered by the later for loop condition, i.e., `len(matches)-backups`.
I added the explicit return to avoid sorting the existing data file names.
=> refactor: return explicitly when no need to clean backup files

README.md, cmd/easeprobe/main.go, conf/conf.go, probe/data.go, probe/data_test.go
fixes #98 
```shell
$ ./easeprobe -v                                                                                                                                  ─╯
EaseProbe v1.5.0
```
```shell
$ ./easeprobe -h                                                                                                                                  ─╯
Usage of build/bin/easeprobe:
-d    dry notification mode
-f string
configuration file (default "config.yaml")
-v    prints version
```
```yaml
version : 1.5.0
```
```yaml
---
name: EaseProbe
version: v1.5.0
---
Probe:
...
....
```
=> Versionizing the binary, config, data file

.github/workflows/ci.yaml, probe/client/postgres/postgres.go
This PR 
* Silences the stutters warning we receive from the Postgres probe
* restores the permissions for `GITHUB_WORKSPACE` after the checks to get rid of the following notice.
=> (minor) ci workflow restore GITHUB_WORKSPACE permissions

README.md, go.mod, go.sum, notify/notify.go, notify/teams/teams.go
=> Introduce Teams support

channel/channel.go, channel/manager.go, cmd/easeprobe/channel.go, cmd/easeprobe/report.go, notify/aws/sns.go, notify/base/base.go, notify/dingtalk/dingtalk.go, notify/discord/discord.go, notify/email/email.go, notify/lark/lark.go, notify/log/log.go, notify/notify.go, notify/slack/slack.go, notify/sms/conf/conf.go, notify/sms/nexmo/nexmo.go, notify/sms/sms.go, notify/sms/twilio/twilio.go, notify/sms/yunpian/yunpian.go, notify/teams/teams.go, notify/telegram/telegram.go, notify/wecom/wecom.go
For the Probe interface, the method `Name()` retrieves the name, and the `Channels()` retrieve all channels. However, the Notify interface have different method `GetName()` and `GetChannels()`.
So, this PR makes us use the same naming convention. 
`GetName()` -> `Name()`
`GetChannel()` -> `Channel()`
For the `Probe` interface, the `Kind()` is implemented by the base prober, however, for the `Notify` interface, the `Kind()` is implemented by each concrete notifier. So, move the `Kind()` from the concrete notifier to the base notifier.
=> Refactoring the Notify interface to align with Probe interface

README.md, notify/log/format.go, notify/log/log.go, notify/log/log_unix.go, notify/log/log_windows.go, report/result.go, report/sla.go, report/types.go
Support the local file log and syslog . 
**Note**: syslog doesn't support the Windows platform.
```yaml
notify:
log:
- name: log file # local log file
file: /var/log/easeprobe.log
- name: Remote syslog # syslog ((!!! Not For Windows !!!))
file: syslog # <-- must be "syslog" keyword
host: 127.0.0.1:514 # remote syslog server - optional
network: udp #remote syslog network [tcp, udp] - optional
```
```log
2022-06-07T12:15:50+08:00 MacBookPro EaseProbeBot[17652]: title="TLS Test Failure"; status="down"; name="TLS Test"; endpoint="https://localhost:8443/hello"; rtt="2ms"; time="2022-06-07 04:15:50 UTC"; message="Error (http): Error: Get "https://localhost:8443/hello": dial tcp [::1]:8443: connect: connection refused"
```
```syslog
2022-06-07T12:14:35+08:00 MacBookPro EaseProbeBot[17652]: …
```
=> feat: support the syslog notification

README.md, global/global.go, global/global_test.go, notify/notify.go, notify/shell/shell.go, probe/common.go, probe/common_test.go, probe/host/host.go, probe/shell/shell.go, probe/ssh/ssh.go, report/result.go, report/result_test.go, report/sla.go, report/types.go, resources/scripts/notify/notify.sh
EaseProbe set the following environment variables
- `$EASEPROBE_TYPE`:  two types of message:`Status` or `SLA`
If the TYPE is Status, the following environment variables would be set
- `$EASEPROBE_NAME`: probe name
- `$EASEPROBE_STATUS`: "up" or "down"
- `$EASEPROBE_RTT`: round trip time in milliseconds
- `$EASEPROBE_TIMESTAMP`: timestamp of probe time
- `$EASEPROBE_MESSAGE`: probe the message
And EaseProbe offers two formats for both probe status and SLA report
- `$EASEPROBE_JSON`: the JSON format
- `$EASEPROBE_CSV`: the CSV format
The CVS format would be set to STDIN for the shell command. 
```
Type: Status
----------------------------------------------------
Title: TLS Test Recovery - ( 19m24s Downtime )
Name: TLS Test
Status: up
RTT: 42000000
TIMESTAMP: 1654588743532
Message: - …
```
=> feat: support shell notification

probe/client/kafka/kafka.go, probe/client/mongo/mongo.go, probe/client/mysql/mysql.go, probe/client/zookeeper/zookeeper.go, probe/client/zookeeper/zookeeper_test.go
This PR changes the comment for our various clients from Redis to their appropriate names. It also fixes a bug in a test case where we tested with the Redis driver on the Zookeeper test case.
=> [minor] Copy paste typo

cmd/easeprobe/main.go, cmd/easeprobe/notify.go, cmd/easeprobe/probe.go, conf/conf_test.go, probe/client/client.go
This PR introduces the following changes
=> Remove probes with fail config

README.md, go.mod, go.sum, probe/client/client.go, probe/client/conf/conf.go, probe/client/conf/conf_test.go, probe/client/memcache/memcache.go, probe/client/memcache/memcache_test.go
This PR adds support for Memcache client probe
```yaml
client:
- name: Memcache
driver: "memcache"
host: "localhost:11211" # host to query
data:
"sysconfig:event_active": "1" # Check the namespaced key `sysconfig:event_active` has value `1` and fail if not
mykey: "value" # Check the key `mykey` has value `value` and fail if not
mykeywithnovalcheck:  # Just check the existence of key
```
@haoel i am currently stuck with this. I will need help with the following
1. I cant figure out how to make it populate the Key/Value pairs from the config my m.Key and m.Value are always nil
2. I cant figure out how to utilize ctx with the Memcache Get() and New()
=> Memcache client

README.md, probe/host/host.go, probe/host/host_test.go, probe/host/metrics.go
the original host probe only supports root disk usage check.
the PR allows user to configure multiple disks. if not configure the "disks", the default behavior just check the root fs.
```yaml
host:
servers:
- name: server
host: user@1.1.1.1
....
disks:
- /
- /data
```
=> feat: support multiple disks usage check for host probe

notify/discord/discord.go
Currently, the SLA report in Discord reports the Uptime and Downtime in the following format:
Up: `785h39m0s`   <- 785 hours is too large
It should be: 
Up:  `32d17h39m0s`  <- 32 days and 17 hours would be better.
The second format is used by all notifications.
=> Using DurationStr() format Discord Uptime and DownTime

README.md, global/global.go, metric/prometheus.go, metric/prometheus_test.go, probe/http/http.go, probe/http/metrics.go, probe/http/trace.go, probe/http/trace_test.go, probe/tls/metrics.go
the following tracing metrics have been added:
- **dns**: get the ip address, from `dnsStartAt()` to  `dnsDone()`
- **conn**: tcp connection,  from `connectStart()` to `connectDone()`
- **tls**: tls connection, from `tlsStart()` to `tlsDone()`
- **send**: send the http header, from `wroteHeaderField()` to `wroteHeaders()`
-  **wait**: send the http request, from `wroteRequest()` to `gotFirstResponseByte()`
- **transfer** : wait all of data received, from `gotFirstResponseByte()` to `putIdleConn()` 
- **total**: from the beginning to the end. `getConn()` to `putIdleConn()`
```
total >= DNS + conn + tls + send + wait +transfer 
```
it can be seen in Prometheus and Grafana, the following snapshot is an example.
open the debug log, you will see the following debug information
```log …
```
=> feat: Add HTTP Probe trace time metrics

README.md, report/result_test.go, report/sla.go, report/sla_test.go, web/server.go
For the HTML report, add the following options:
- `status=up`: only shows the probers which status is `up`. the value can be `up` or `down`.
- `gte=50`: only shows the probers the SLA percentage is >= `50%`.
- `lte=90`: only shows the probers the SLA percentage s  <= `90%`.
=> Add some filter options for SLA HTML Page

cmd/easeprobe/probe.go
To avoid all probers starting at the same time, each prober delays the start time and all of them have an equal distribution.
This enhancement would improve the performance of the EaseProbe.
=> Enhancement: Equally distributing start the probers.

probe/http/http.go, probe/ssh/ssh.go, probe/tcp/tcp.go, probe/tls/tls.go
EaseProbe would create and close a new TCP connection every time, this would cause many TIME_WAIT connections 
To solve this, we can set `SO_LINGER=0`, so the closed TCP connect won't have TIME_WAIT status.
Reference: https://stackoverflow.com/questions/3757289/when-is-tcp-option-so-linger-0-required
=> set the `SO_LINGER=0` to tcp, http, tls, ssh probe

README.md, cmd/easeprobe/probe.go
This PR changes the start up delay of the probers.
if probers are less than 60 then just use 1 second delay instead
=> Change the start up delay if we have less than 60 probers

cmd/easeprobe/main.go, cmd/easeprobe/probe.go, cmd/easeprobe/report.go, probe/base/base.go, probe/data.go, probe/result.go, report/filter.go, report/filter_test.go, report/result_test.go, report/sla.go, report/sla_test.go
We have a map to collect all of the probers' probe results, all of the probers would set its result into this map concurrently in a different key(this is not a problem), however, we have another go routine that persistent this map periodically, this causes the "**concurrent map iteration and map write**" problem and it makes EaseProbe crash.
the stake trace of the crash as below:
```st
fatal error: concurrent map iteration and map write
goroutine 50 [running]:
runtime.throw({0xfd17f1?, 0x0?})
/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0172745f0 sp=0xc0172745c0 pc=0x438b31
runtime.mapiternext(0x0?)
/usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc017274660 sp=0xc0172745f0 pc=0x41058b
runtime.mapiterinit(0xc0172747e8?, 0xc0265008d0?, 0xc017274710?) …
```
=> Fix the concurrent map access crashing problem

notify/lark/lark.go, report/result.go, report/sla.go
This PR fix fails to send a notification to Lark(Feishu): `code: 9499, msg: bad request`.
This error is found in the Feishu document: https://open.feishu.cn/document/ukTMukTMukTM/ugjM14COyUjL4ITN
=> bug-fix: Lark(Feishu) notifications don't work

README.md, probe/client/client.go, probe/client/client_test.go, probe/client/conf/conf.go, probe/client/conf/conf_test.go, probe/client/kafka/kafka.go, probe/client/kafka/kafka_test.go, probe/client/memcache/memcache.go, probe/client/memcache/memcache_test.go, probe/client/mongo/mongo.go, probe/client/mongo/mongo_test.go, probe/client/mysql/mysql.go, probe/client/mysql/mysql_test.go, probe/client/postgres/postgres.go, probe/client/postgres/postgres_test.go, probe/client/redis/redis.go, probe/client/redis/redis_test.go, probe/client/zookeeper/zookeeper.go, probe/client/zookeeper/zookeeper_test.go
```yaml
client:
- name: Redis Native Client (local)
driver: "redis"  # driver is redis
host: "localhost:6379"  # server and port
data:         # Optional
key: val    # Check that `key` exists and its value is `val`
```
```yaml
client
- name: MySQL Native Client (local)
driver: "mysql"
host: "localhost:3306"
data: # Optional, check the specific column value in the table
"test:product:name:id:1" : "EaseProbe" # select name from test.product where id = 1
"test:employee:age:id:2" : 45          # select age from test.employee where id = 2
```
```yaml
client:
- name: MongoDB Native Client (local)
driver: "mongo"
host: "localhost:27017"
data: # Optional, find the specific value in the table
"test:employee" : '{"name":"Hao Chen"}' # find the employee with name "Hao Chen"
"test:product" : …
```
=> feat: Support MySQL/Redis/MongoDB/PostgreSQL/Zookeeper Native Client  to check the data

README.md, probe/http/http.go, probe/http/http_test.go
close #176 
Support the http proxy setting and user-defined User-Agent
Example:
```yaml
http:
- name: Youtube
url: https://youtube.com
proxy:  socks5://localhost:1085
#proxy: https://user:password@proxy.example.com:443
headers:
User-Agent: Customized User-Agent
```
=> support the proxy for HTTP probe and can customized the User-Agent

cmd/easeprobe/main.go
We use `log "github.com/sirupsen/logrus"` for log package:
https://github.com/megaease/easeprobe/blob/88fc4e4dbd0eb2f3d191bff6b7f8697ba85ed75f/cmd/easeprobe/main.go#L37
And we use version 1.9 (show in go.mod)
https://github.com/megaease/easeprobe/blob/88fc4e4dbd0eb2f3d191bff6b7f8697ba85ed75f/go.mod#L17
we use `os.Exit(-1)` after line 88 `log.Fatalln` and line 96 `log.Fatalf`
From [Fatalln doc](https://pkg.go.dev/github.com/sirupsen/logrus@v1.9.0#Fatalln):
> Fatalln logs a message at level Fatal on the standard logger then the process will exit with status set to 1.
So subsequent `os.Exit(-1)` will not executable.
Same with `log.Fatalf`.
So, here are 2 solutions:
option 1: just delete `os.Exit(-1)`;
option 2: change `log.Fatal` to `log.Error`
I think option 2 is more appropriate.
=> change log.Fatal to log.Error to make subsequent os.Exit executable

probe/http/http.go
* https://pkg.go.dev/net/http#Request
// For client requests, Host optionally overrides the Host
// header to send. If empty, the Request.Write method uses
// the value of URL.Host. Host may contain an international
// domain name.
Host string
=> custom host header

conf/log_test.go, probe/http/http_test.go
- **Fix Unit Test failed on Windows platform** - Windows platform seems to leave the removed files a while, which could sometimes cause the unit test to fail.
- **Add the UT for HTTP probe** - test coverage to 100%
=> Improve the Unit Test for `conf` package & HTTP Probe

.gitignore, README.md, docs/CONTRIBUTING.md, docs/Manual.md, notify/sms/nexmo/nexmo.go, notify/sms/twilio/twilio.go, notify/sms/yunpian/yunpian.go, resources/config.yaml
- Move the most content to the `docs/Manual.md`
- Add the HTTP XPath/RegExp expression evaluation in Manual.md
- Add a configuration template - resources/config.yaml
=> Refactoring the README.md

conf/merge_test.go
refer to https://github.com/golang/go/issues/51442
=> using retry loop to remove the temp dir

conf/merge_test.go, eval/eval.go, probe/http/http.go, probe/http/http_test.go
If http probe didn't configure the `eval/doc`,  EaseProbe would report the error - `Unsupported document type: unsupported`
This bug only can be reproduced after PR #192 
here is the fix - check if the `eval` configuration is not configured, then skip the eval configration.
=> bug-fixing: http probe report the unsupported document type

cmd/easeprobe/probe.go, conf/conf.go, docs/Manual.md, global/global.go, global/probe.go, global/probe_test.go, probe/base/base.go, probe/base/base_test.go, probe/data_test.go, probe/result.go, probe/result_test.go, probe/status.go, probe/status_counter.go, probe/status_counter_test.go, probe/status_test.go, resources/config.yaml
This PR supports the failure/success threshold features - we can configure the number of continuously failed/successful probes to determine whether the endpoint status is DOWN or UP.
for example:
```yaml
probe:
failure: 2 # number of consecutive failed probes needed to determine the status down, default: 1
success: 1 # number of consecutive successful probes needed to determine the status down, default: 1
```
close #230
=> feat: support the failure/success threshold for probe

cmd/easeprobe/report.go, docs/Manual.md, resources/config.yaml
The PR is the continuous work for  PR #236, which optimize the following works:
=> Optimizing the SLA Report

.goreleaser.yaml, Makefile, global/global.go, report/result.go, report/sla.go
=> Embed git tags as Version into go binary, remove Slack `channel` field

go.mod, go.sum, notify/email/email.go, notify/email/email_test.go
Hi, I use Email notification and find the following error message:
> [email / test-dev / Notification] Retried to send 3/3 - tls: first record does not look like a TLS handshake
I think it's better to provide an option and let the user choose.
=> Enhance email notification: add an ssl option

conf/conf.go, docs/Manual.md, docs/Roadmap.md, go.mod, go.sum, probe/ping/metrics.go, probe/ping/ping.go, probe/ping/ping_test.go, resources/config.yaml
support the following probe configuration
```yaml
ping:
- name: Localhost
host: 127.0.0.1
count: 5 # number of packets to send, default: 3
lost: 0.2 # 20% lost percentage threshold, mark it down if the loss is greater than this, default: 0
```
=> feat: support ping (icmp) probe

probe/client/postgres/postgres.go, probe/client/postgres/postgres_test.go
close #285 
disable the SSL in `prostgresql.conf` by commenting on the following configuration 
```
#ssl = on
#ssl_ca_file = '/path/to/certs/ca.crt'
#ssl_cert_file = '/path/to/certs/server.crt'
#ssl_key_file = '/path/to/certs/server.key'
```
EaseProbe config.yaml
```yaml
client:
- name: PostgreSQL Native Client (local)
driver: "postgres"
host: "localhost:5432"
username: user
password: password
```
if TLS in the client is not configured,  we need to configure it with a nil
```diff
@@ -62,8 +62,9 @@ func New(opt conf.Options) (*PostgreSQL, error) {
return nil, fmt.Errorf("TLS Config Error - %v", err)
} else if tls != nil {
tls.InsecureSkipVerify = true
-               clientOptions = append(clientOptions, pgdriver.WithTLSConfig(tls))
}
+       // if the tls is nil which means …
```
=> bug-fixing: PostgreSQL failed to check if the server wasn't turn on the SSL

.github/workflows/helm.yaml, docs/Deployment.md, helm/easeprobe/README.md
To automatically release Helm charts, we also need to set up GitHub Pages for this repository @haoel
=> Add Helm charts release workflow

docs/Manual.md, go.mod, go.sum, probe/ping/ping.go, probe/ping/ping_test.go
[go-ping/ping](https://github.com/go-ping/ping) is no longer maintained. Switch to the recommended, actively maintained fork: https://github.com/prometheus-community/pro-bing
https://github.com/go-ping/ping/issues/221
=> chore(deps): replace go-ping with pro-bing

probe/ping/ping.go
`ping.Pinger` contains `sync.RWMutex`, `reflect.ValueOf(*p)` will copy the lock value.
=> refactor: avoid copying mutex

cmd/easeprobe/main.go
Use buffered os.Signal channel as argument to signal.Notify to ensure that we do not drop a signal notification.
=> fix: use buffered os.Signal channel as argument to signal.Notify

Makefile
since #307 introduced the tag for Helm Chart, the PR impacts the easeprobe's build version, because the Makefile always retrieved the latest tag. 
Before this fix:
```shell
> easeprobe -v
EaseProbe easeprobe-helm-charts-v1.0.0 8b36e4424 2023-03-11T01:02:40Z go1.19.4
```
After this fix
```shell
> easeprobe -v                                                                                                                                                                   ─╯
EaseProbe v2.0.1 8b36e4424 2023-03-11T01:02:40Z go1.19.4
```
=> Fix the version bug

docs/Manual.md
There are some links in [docs/Manual.md](https://github.com/megaease/easeprobe/blob/main/docs/Manual.md) are broken, this modification is going to fix it.
=> Fix broken links in user manual

notify/telegram/telegram.go, notify/telegram/telegram_test.go
=> Split long message for Telegram bot

report/sla.go
SLA Report 默认 HTML 显示状态是乱序的，在展示之前添加了排序。
=> Optimize the ordering of status display in the SLA report

probe/client/kafka/kafka.go
Currently, for the Kafka client, the timeout is only applicable during the dialing process. Once the connection is established and conn.ReadPartitions is called, it may experience significant delays. This situation can occur if the Kafka server is unresponsive or slow to write responses, potentially taking several minutes. To address this issue, this pr introduces a timeout setting for the connection.
This may cause the problem in issue #442 .
=> set timeout for kafka client conn

notify/dingtalk/dingtalk.go
As discussed in #467 , DingTalk may return error code of 40035 (potential caused by invalid json payload). This pr use golang struct to make sure that payload is valid json even meet some specially characters.
=> make sure dingtalk notify always produce valid json

resources/Dockerfile.goreleaser
In `.goreleaser.yaml`, we put easeprobe binary in `bin/easeprobe`.
```
builds:
- id: build
main: ./cmd/easeprobe/
binary: bin/easeprobe
```
then when use it, we should copy it from `bin/easeprobe`. 
the old version of goreleaser works but after a new version of goreleaser, this will cause panic of release process.
=> fix goreleaser bug

probe/websocket/ws_test.go
There were some random test failures for TestWSPing, as shown [here](https://github.com/megaease/easeprobe/actions/runs/7487393962/job/20379697928#step:5:1151).
These failures should emerged when the test cases began running before the http server was ready.
=> Avoid random websocket test failures by waiting for http server to start

notify/aws/sns.go, notify/aws/sns_test.go, notify/dingtalk/dingtalk.go, notify/dingtalk/dingtalk_test.go, notify/discord/discord.go, notify/email/email.go, notify/email/email_test.go, notify/lark/lark.go, notify/lark/lark_test.go, notify/log/log_test.go, notify/ringcentral/ringcentral.go, notify/ringcentral/ringcentral_test.go, notify/slack/slack.go, notify/slack/slack_test.go, notify/sms/nexmo/nexmo.go, notify/sms/nexmo/nexmo_test.go, notify/sms/twilio/twilio.go, notify/sms/twilio/twilio_test.go, notify/sms/yunpian/yunpian.go, notify/sms/yunpian/yunpian_test.go, notify/teams/teams.go, notify/teams/teams_test.go, notify/telegram/telegram_test.go, notify/wecom/wecom.go, notify/wecom/wecom_test.go
As highlighted in issues #468 and #467, users of EaseProbe encounter difficulties in diagnosing problems when a notification fails to send. The primary challenge lies in the limited information provided by the error messages, which typically consist only of an error code and a brief description. To effectively troubleshoot, users require more detailed data, specifically the request body sent to the notification server.
This PR introduces an enhancement that appends the request body to the error message. With this change, users will receive comprehensive information regarding the failed notification attempt. This addition enables users to easily identify the content sent to the notification server, facilitating quicker and more accurate problem resolution.
=> log notify error with request body

probe/tls/tls.go
fix #496 which was introduced by https://github.com/megaease/easeprobe/pull/386/files#diff-f4ba94b6ceb9d73b8797e5ca558f756010112d0d6b71ca4ffcdf3da10fbe2c1f
=> fix tls metrics

probe/base/base.go
Fix #523 
In `channel.go` within the `Channel.WatchEvent` function, the code checks `result` and uses its information to decide whether to send a notification. However, in `notification_strategy.go`, the `NotificationStrategyData.ProcessStatus` function updates the status and the number of notifications sent.
This means that in the case of #523, since the failure count is set to 2 and a failure occurs in the `init` state, the channel does not send a notification because it is in the `init` state. However, `NotificationStrategyData` considers the notification already sent and `IsExceedMaxTimes` returns true.
As a result, no notification is sent. To fix this problem, when in the init state, `NotificationStrategyData` should not be updated. According to the logic and comments in …
=> fix multi failure notify

probe/ping/ping.go
- gauge metric should be SET value, not ADD.
- fix MaxRtt metric loss.
=> fix: metric EaseProbe_ping_loss Add by mistake

docs/Manual.md, probe/http/http.go, probe/ssh/ssh.go, probe/tcp/tcp.go, probe/tls/tls.go
The following PR is an attempt to make SO_LINGER option configurable. 
It introduces a new `bool` option named `nolinger` for tcp, tls, http and ssh probes which disables `SO_LINGER`. Default value set to `false` to match the previous easeprobe operation and not require configuration changes when updated.
Documentation also updated to include the addition of this option.
Notes:
* Needs testing (i am unable to test it currently)
* I dont know how to implement the new option for our test cases.
=> Make linger configurable

docs/Manual.md, probe/common.go, probe/common_test.go
This PR add a `with_output` option that, when enabled, appends the output to the error message. 
This way, if an error occurs, users can immediately see what happened, making it easier to diagnose and resolve issues.
=> add option to print output when meet error

.github/workflows/release.yaml, .gitignore, .goreleaser.yaml
based on [goreleaser doc](https://github.com/goreleaser/goreleaser/blob/599ce44c749ef13b4e6a3042ece90aa3e3f3dcaa/www/docs/deprecations.md#--rm-dist) `--rm-dist` is removed and we should use `--clean` instead.
=> udpate release.yaml

.github/workflows/helm-lint.yaml
Python 3.7 is not supported on GitHub Actions ubuntu-latest runner: https://github.com/actions/setup-python/issues/962
Python 3.7 has reached EOL more than 1 year ago anyway, so not worth the effort supporting it.
=> Update Python version to 3.8 in helm-lint.yaml

.github/workflows/test.yaml
There have been changes in `ubuntu-latest` that caused `TestPing` to fail across all PRs. This PR addresses and resolves the issue.
=> Update privilege to fix TestPing on latest ubuntu

probe/host/cpu.go
top -b -n 1 | grep Cpu | awk -F ":" '{print $2}'
在一些场景中，会得到这样的结果
```sh
[root@myserver ~]# top -b -n 1 | grep Cpu | awk -F ":" '{print $2}'
16.1 us,  2.0 sy,  0.0 ni, 80.2 id,  0.0 wa,  0.2 hi,  1.5 si,  0.0 st
00.00 grep --color=auto Cpu
```
而非预想的
```sh
[root@tuo-3-201 ~]# top -b -n 1 | grep Cpu | awk -F ":" '{print $2}'
16.1 us,  2.0 sy,  0.0 ni, 80.2 id,  0.0 wa,  0.2 hi,  1.5 si,  0.0 st
```
如果使用
top -b -n 1 | grep [C]pu | awk -F ":" '{print $2}'
就能完美解决
=> Resolve compatibility issues
