megaease/easeprobe

Makefile, README.md, cmd/easeprobe/main.go, global/global.go, global/notify.go, notify/discord/discord.go, notify/email/email.go, notify/log/log.go, notify/notify.go, notify/slack/slack.go, notify/telegram/telegram.go, probe/common.go, probe/probe.go, probe/result.go
This PR includes the following changes
- Add telegram notify (#6)
- Discord notify can customize the avatar and thumbnail
- Add the `timeout `& `name` for notify.
- Refactory the notify retry code.
=> feat(notify): support telegram notification and notify code refactory

README.md, conf/conf.go, notify/notify.go, notify/wecom/wecom.go
add wecom rebot notify support (https://developer.work.weixin.qq.com/document/path/91770).
closes  #5
=> :sparkles: (notify) add wecom notify support

probe/base/base.go, probe/common.go, probe/http/http.go, probe/ssh/ssh.go, resources/scripts/build-image.sh, resources/scripts/copyright.sh
1) add the license comment 
2) adjust the probe log
3) refine the shell script
=> Add license comment and refine the log and shell scripts

Makefile, probe/client/mongo/mongo.go, probe/client/mysql/mysql.go, probe/client/postgres/postgres.go
>There are also log level optimizations, and build.
=> Improve null pointer exception when TLS is not configured

resources/Dockerfile
this PR is because the PR #31 change the go build arguments
=> update the dockerfile due to compile arguments changed

conf/conf.go
This PR adds env support in YAML.
exmaple:
```yaml
notify:
telegram: 
- token: ${TELEGRAM_TOKEN}
```
=> feat: add env variables replace to yaml

README.md, conf/conf.go, go.mod, go.sum, probe/ssh/ssh.go
- upgrade the yaml package to v3
- slightly adjust the README.md
- `go fmt ./...`
=> Upgrade the Yaml package from v2 to v3

cmd/easeprobe/main.go, conf/conf.go
Add feature to fetch config from internet
=> feat: add fetch config from internet

cmd/easeprobe/main.go, conf/conf.go, notify/dingtalk/dingtalk.go
=> remove function configNotifiers useless parameters

.goreleaser.yaml
=> Add openbsd platform (issue#54)

README.md
update README.md link to host.go to point to current branch
=> update README.md link to host.go

README.md
Document some of the changes from #36
=> Document changes from #36

README.md, web/server.go
the api url doesnt work with a / at the end
=> the api url doesnt work with a / at the end

README.md, cmd/easeprobe/main.go, conf/conf.go, global/global.go, probe/base/base.go, probe/data.go, probe/result.go, probe/result_test.go, probe/results_test.go, probe/status.go, report/result.go, report/sla.go
This PR mainly addresses issue #69.  And it makes the following changes.
- Maintain a map[name]*Result data store.
- Persisting all of probers results (SLA data) into a YAML file periodically 
- Load the SLA data YAML file when startup.
- Gracefully process shutdown and persist the data before exit.
- Set the UTC time locale for all `time.Now()`
```
┌──────┐    ┌──────┐       ┌──────┐
│prober│    │prober│       │prober│
├──────┤    ├──────┤  .....├──────┤
│Result│    │Result│       │Result│
└───▲──┘    └──▲───┘       └───▲──┘
│          │               │
│          │ref            │
│ref   ┌───┴────────────┐  │ref
└──────┤    KV Store    ├──┘
│ <Name, Result> │
└────────────────┘
probe/data.go
│    ▲
▼    │
$CWD/data/data.yaml
( config - settings.sla.data )
```
```
Remove probe data
Read …
```
=> feat: persisting the SLA data into disk and reload it while start

README.md, conf/conf.go, daemon/daemon.go, global/easeprobe.go, global/global.go, notify/discord/discord.go, probe/client/mysql/mysql.go, report/common.go, report/result.go, report/sla.go
=> Support the customized discord name and icon

README.md, resources/Dockerfile, resources/scripts/entrypoint.sh
* minor changes from `would` to `will` readme
* added mention on README for docker image use and release download
* added environment variable on Dockerfile `PROBE_CONFIG`
* Updated entrypoint.sh to set default value if not set for `PROBE_CONFIG`
* Removed `-f /opt/config.yaml` from default entrypoint action
=> Minor Dockerfile/entrypoint.sh edit and documentation updates

cmd/easeprobe/main.go
My previous PR #92 introduced a bug that caused it to skip data.yaml creation
=> (bug): disabling save with wrong condition :facepalm:

notify/wecom/wecom.go, report/result.go
=> Bugfix:Content is truncated to send markdown msg on wecom webhook(#101)

README.md, conf/conf.go, probe/tls/metrics.go, probe/tls/tls.go, probe/tls/tls_test.go
TLS ping to remote endpoint, can probe for revoked or expired certificates
=> introduce tls probe

README.md, docs/CONTRIBUTING.md
This PR introduces a contributing guide documentation to assist in the on-boarding process of new developers into the project.
Most of the work is done by @haoel :tulip:
=> Add contributing guide

README.md, docs/CONTRIBUTING.md, docs/Roadmap.md
This PR updates the readme, roadmap and contributing guide to be synced with the latest project changes
=> Documentation updates

channel/channel.go, channel/manager.go, cmd/easeprobe/main.go
when I refactor the code to support the channel, I missed this function.
=> bug-fix: command line option dry notification not working

README.md, probe/ssh/endpoint.go, probe/ssh/endpoint_test.go
Provide password configuration of privatekey
=> Add some privatekey password options

Makefile
=> Fix the go 1.19 build error

README.md, docs/Manual.md, notify/notify.go, notify/ringcentral/ringcentral.go, notify/ringcentral/ringcentral_test.go, resources/config.yaml, resources/schema.json
Please check here for how to create a webhook in RingCentral. https://developers.ringcentral.com/guide/team-messaging/incoming-webhooks/webhook-creation.
- Failure notify
- Recovery notify
- SLA report
Please help review, thanks.
=> feature(notify): support RingCentral webhook

.github/workflows/test.yaml, go.mod, go.sum
upgrade the unit test golang version from v1.18 to v1.19 to address this issue https://github.com/golang/go/issues/51442
=> using go 1.19 to run unit test

docs/Manual.md, report/result.go, report/result_test.go, resources/scripts/notify/notify.sh
=> Add EASEPROBE_TIME to shell env

eval/eval.go, eval/eval_test.go, probe/http/http.go
This  expression value could be helpful
=> send the expression value if evaluation is false

docs/Manual.md, probe/base/base.go, probe/base/metrics.go, probe/result.go
- Optimizing the SLA total metrics
- Adding the SLA total time metrics
=> Optimizing and adding new SLA prometheus  metrics

web/server.go
=> Fix XSS attack bug

docs/Manual.md
The major work just reconstruct the Probe section by moving the contents from the `configuration` section into the `probe` section
=> Reconstructing the user manual

.github/workflows/helm-lint.yaml, .github/workflows/helm-release.yaml, ctconfig.yaml, helm/easeprobe/Chart.yaml, helm/easeprobe/values.yaml
1. use `easeprobe-helm-charts-v{{ .Version }}` as release name template
2. add Helm lint workflow
=> Optimize helm release

notify/ringcentral/ringcentral.go, notify/slack/slack.go, notify/wecom/wecom.go, report/result.go, report/sla.go
In some special cases, json may failed to escape. This pr log errors in these cases and help user to find bug quickly.
=> log error when meet invalid json

docs/Manual.md
Minor edit to mention `$` sign and environment variable expansion.
issue #673
=> Minor edit to mention `$` sign and environment variable expansion
